services:
  api:
    build: .
    environment:
      - MONGO_HOST=db 
      - MONGO_PORT=27017
      - MONGO_DB_NAME=Tarpaulin
      - MONGO_USER=Tarpaulin
      - MONGO_PASSWORD=hunter2
      - PORT=8069
    ports:
      - "8069:8069"
    restart: on-failure
    depends_on:
      - dbinit

  db: 
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=hunter2
    # Get rid of ports field on production build
    ports:
      - "27017:27017"
    volumes: 
      - dbstorage:/data/db

  dbinit:
    image: mongo 
    volumes:
      - ./mnt:/mnt
    depends_on:
      - db
    command: /mnt/init-db.sh

volumes:
  dbstorage:
